export const FETCH_CUISINES = "FETCH_CUISINES";
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const UPDATE_CUISINES = "UPDATE_CUISINES";
export const UPDATE_RESTAURANTS = "UPDATE_RESTAURANTS";
export const CUISINES_LOADING = "CUISINES_LOADING";
export const RESTAURANTS_LOADING = "RESTAURANTS_LOADING";
export const FETCH_CUISINES_FAILURE = "FETCH_CUISINES_FAILURE";
export const FETCH_RESTAURANTS_FAILURE = "FETCH_RESTAURANTS_FAILURE";



